name: Scrape

on:
  push:
  workflow_dispatch:
  schedule:
  - cron:  '2,22,42 * * * *'

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Scrape
      run: |
        mkdir -p fplmaps.com
        curl 'https://www.fplmaps.com/customer/outage/StormFeedRestoration.json' \
          | jq > fplmaps.com/StormFeedRestoration.json
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git pull --rebase
        git push
